CREATE DATABASE Farmaceutica

go
use Farmaceutica
go

-- TABLAS SATELITE

CREATE TABLE PAISES(
	ID_PAIS INT IDENTITY(5,5),
	PAIS VARCHAR(50)NOT NULL,
	CONSTRAINT PK_PAISES PRIMARY KEY(ID_PAIS)
)

CREATE TABLE PROVINCIAS(
	ID_PROVINCIA INT IDENTITY(5,5),
	PROVINCIA VARCHAR(50)NOT NULL,
	ID_PAIS INT NOT NULL,

	CONSTRAINT PK_PROVINCIAS PRIMARY KEY(ID_PROVINCIA),
	CONSTRAINT FK_PROVINCIAS_PAISES FOREIGN KEY(ID_PAIS)
	REFERENCES PAISES(ID_PAIS)
)

CREATE TABLE CIUDADES(
	ID_CIUDAD INT IDENTITY(5,5),
	CIUDAD VARCHAR(50)NOT NULL,
	ID_PROVINCIA INT NOT NULL,

	CONSTRAINT PK_CIUDADES PRIMARY KEY(ID_CIUDAD),
	CONSTRAINT FK_CIUDADES_PROVINCIAS FOREIGN KEY(ID_PROVINCIA)
	REFERENCES PROVINCIAS(ID_PROVINCIA)
)

CREATE TABLE BARRIOS(
	ID_BARRIO INT IDENTITY(5,5),
	BARRIO VARCHAR(50)NOT NULL,
	ID_CIUDAD INT NOT NULL,
	CONSTRAINT PK_BARRIOS PRIMARY KEY(ID_BARRIO),
	CONSTRAINT FK_BARRIOS_CIUDADES FOREIGN KEY(ID_CIUDAD)
	REFERENCES CIUDADES(ID_CIUDAD)
)

CREATE TABLE ESTABLECIMIENTOS (
    ID_ESTABLECIMIENTO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
    ID_BARRIO INT NOT NULL,
    CONSTRAINT PK_ESTABLECIMIENTO PRIMARY KEY (ID_ESTABLECIMIENTO),
    CONSTRAINT FK_ESTABLECIMIENTO_BARRIOS FOREIGN KEY (ID_BARRIO) 
        REFERENCES BARRIOS(ID_BARRIO)
);

CREATE TABLE TIPOS_PRODUCTOS (
    ID_TIPO_PRODUCTO INT NOT NULL,
    TIPO_PRODUCTO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPOS_PRODUCTOS PRIMARY KEY (ID_TIPO_PRODUCTO)
);


CREATE TABLE PRESENTACIONES (
    ID_PRESENTACION INT NOT NULL,
    PRESENTACION VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PRESENTACIONES PRIMARY KEY (ID_PRESENTACION)
);



CREATE TABLE CARGOS (
    ID_CARGO INT NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CARGOS PRIMARY KEY (ID_CARGO)
);

CREATE TABLE TIPOS_MOVIMIENTOS (
    ID_TIPO_MOV INT NOT NULL,
    MOVIMIENTO VARCHAR(100) NOT NULL,
	MODIFICADOR int not null,
    CONSTRAINT PK_TIPOS_MOVIMIENTOS PRIMARY KEY (ID_TIPO_MOV)
);

CREATE TABLE TIPOS_CONTACTOS (
    ID_TIPO_CONTACTO INT NOT NULL IDENTITY (1,1),
    TIPO_CONTACTO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPOS_CONTACTOS PRIMARY KEY (ID_TIPO_CONTACTO)
);

CREATE TABLE TIPOS_DOCUMENTOS (
    ID_TIPO_DOC INT NOT NULL IDENTITY(1,1),
    TIPO_DOCUMENTO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPOS_DOC PRIMARY KEY (ID_TIPO_DOC)
);

CREATE TABLE TIPOS_GENEROS (
    ID_GENERO INT NOT NULL,
    NOMBRE_GENERO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_GENEROS PRIMARY KEY (ID_GENERO)
);

CREATE TABLE LABORATORIOS (
    ID_LABORATORIO INT NOT NULL,
    NOMBRE_LABORATORIO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_LABORATORIOS PRIMARY KEY (ID_LABORATORIO)
);

CREATE TABLE MARCAS (
    ID_MARCA INT NOT NULL,
    NOMBRE_MARCA VARCHAR(100) NOT NULL,
    CONSTRAINT PK_MARCAS PRIMARY KEY (ID_MARCA)
);

CREATE TABLE MONODROGAS (
    ID_MONODROGA INT NOT NULL,
    MONODROGA VARCHAR(100) NOT NULL,
    CONSTRAINT PK_MONODROGAS PRIMARY KEY (ID_MONODROGA)
);

CREATE TABLE ESPECIALIDADES (
    ID_TIPO_ESPECIALIDAD INT NOT NULL,
    ESPECIALIDAD VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ESPECIALIDADES PRIMARY KEY (ID_TIPO_ESPECIALIDAD)
);

CREATE TABLE TIPOS_PAGOS (
    ID_TIPO_PAGO INT identity(1,1),
    TIPO_PAGO VARCHAR(100) NOT NULL,
	DESCUENTO DECIMAL(5,2) NULL
    CONSTRAINT PK_TIPOS_PAGOS PRIMARY KEY (ID_TIPO_PAGO)
);

-- PRODUCTOS

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_MARCA INT,
    TIPO_PRODUCTO INT NOT NULL,
    DESCRIPCION VARCHAR(255),
    PRECIO DECIMAL(10, 2) NOT NULL,
	ACTIVO BIT NULL,

    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTOS_TIPOS_PRODUCTOS FOREIGN KEY (TIPO_PRODUCTO) 
        REFERENCES TIPOS_PRODUCTOS(ID_TIPO_PRODUCTO),
    CONSTRAINT FK_PRODUCTOS_MARCAS FOREIGN KEY (ID_MARCA) 
        REFERENCES MARCAS(ID_MARCA)
);

CREATE TABLE MEDICAMENTOS (
    ID_MEDICAMENTO INT NOT NULL,
    ID_MONODROGA INT NOT NULL,
    NOMBRE_COMERCIAL VARCHAR(100) NOT NULL,
    ID_LABORATORIO INT NOT NULL,
    ID_MARCA INT NOT NULL,
    VENTA_LIBRE BIT NOT NULL,
    ID_PRESENTACION INT NOT NULL,
    DESCRIPCION VARCHAR(255),
    PRECIO DECIMAL(10, 2) NOT NULL,
	ACTIVO BIT NULL,

    CONSTRAINT PK_MEDICAMENTOS PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT FK_MEDICAMENTOS_MONODROGAS FOREIGN KEY (ID_MONODROGA) 
        REFERENCES MONODROGAS(ID_MONODROGA),
    CONSTRAINT FK_MEDICAMENTOS_LABORATORIOS FOREIGN KEY (ID_LABORATORIO) 
        REFERENCES LABORATORIOS(ID_LABORATORIO),
    CONSTRAINT FK_MEDICAMENTOS_MARCAS FOREIGN KEY (ID_MARCA) 
        REFERENCES MARCAS(ID_MARCA),
    CONSTRAINT FK_MEDICAMENTOS_PRESENTACIONES FOREIGN KEY (ID_PRESENTACION) 
        REFERENCES PRESENTACIONES(ID_PRESENTACION)
);

CREATE TABLE MEDICAMENTOS_LOTES (
    ID_MEDICAMENTO_LOTE INT NOT NULL,
    ID_MEDICAMENTO INT NOT NULL,
    LOTE VARCHAR(50) NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    CONSTRAINT PK_MEDICAMENTOS_LOTES PRIMARY KEY (ID_MEDICAMENTO_LOTE),
    CONSTRAINT FK_MEDICAMENTOS_LOTES_MEDICAMENTOS FOREIGN KEY (ID_MEDICAMENTO) 
        REFERENCES MEDICAMENTOS(ID_MEDICAMENTO)
);

CREATE TABLE OBRA_SOCIAL (
    ID_OBRA_SOCIAL INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_OBRA_SOCIAL PRIMARY KEY (ID_OBRA_SOCIAL)
);

CREATE TABLE TIPOS_COBERTURAS (
    ID_TIPO_COBERTURA INT NOT NULL,
    ID_OBRA_SOCIAL INT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
	DESCUENTO DECIMAL (5,2) NULL
    CONSTRAINT PK_TIPOS_COBERTURAS PRIMARY KEY (ID_TIPO_COBERTURA),
    CONSTRAINT FK_TIPOS_COBERTURAS_OBRA_SOCIAL FOREIGN KEY (ID_OBRA_SOCIAL) 
        REFERENCES OBRA_SOCIAL(ID_OBRA_SOCIAL)
);



CREATE TABLE CLIENTES (
    ID_CLIENTE INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
    ID_BARRIO INT NOT NULL,
    TIPO_DOC INT NOT NULL,
    NRO_DOC VARCHAR(20) NOT NULL,
	ID_GENERO INT
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT FK_CLIENTES_BARRIOS FOREIGN KEY (ID_BARRIO) 
        REFERENCES BARRIOS(ID_BARRIO),
    CONSTRAINT FK_CLIENTES_TIPO_DOC FOREIGN KEY (TIPO_DOC) 
        REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOC),
	CONSTRAINT FK_CLIENTES_GENEROS FOREIGN KEY (ID_GENERO)
		REFERENCES TIPOS_GENEROS (ID_GENERO)
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT NOT NULL,
    RAZON_SOCIAL VARCHAR(100) NOT NULL,
    CUIT VARCHAR(20) NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
    ID_BARRIO INT NOT NULL,
    ACTIVO BIT NOT NULL,
    CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT FK_PROVEEDORES_BARRIOS FOREIGN KEY (ID_BARRIO) 
        REFERENCES BARRIOS(ID_BARRIO)
);

CREATE TABLE EMPRESA_LOGISTICA (
    CUIT VARCHAR(20) NOT NULL,
    NOMBRE_EMPRESA VARCHAR(100) NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
    ID_BARRIO INT NOT NULL,
    CONSTRAINT PK_EMPRESA_LOGISTICA PRIMARY KEY (CUIT),
    CONSTRAINT FK_EMPRESA_LOGISTICA_BARRIOS FOREIGN KEY (ID_BARRIO) 
        REFERENCES BARRIOS(ID_BARRIO)
);


CREATE TABLE PERSONAL (
    ID_PERSONAL INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
	ID_BARRIO INT NOT NULL,
    TIPO_DOC INT NOT NULL,
    NRO_DOC VARCHAR(20) NOT NULL,
	ID_GENERO INT,
	PSW VARCHAR(15),
    CONSTRAINT PK_PERSONAL PRIMARY KEY (ID_PERSONAL),
    CONSTRAINT FK_PERSONAL_TIPO_DOC FOREIGN KEY (TIPO_DOC)
        REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOC),
	CONSTRAINT FK_PERSONAL_GENEROS FOREIGN KEY (ID_GENERO)
		REFERENCES TIPOS_GENEROS (ID_GENERO),
	CONSTRAINT FK_PERSONAL_BARRIOS FOREIGN KEY (ID_BARRIO)
		REFERENCES BARRIOS (ID_BARRIO)
);

CREATE TABLE MEDICOS (
    MATRICULA VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    ID_TIPO_ESPECIALIDAD INT NOT NULL,
    CONSTRAINT PK_MEDICOS PRIMARY KEY (MATRICULA),
    CONSTRAINT FK_MEDICOS_ESPECIALIDADES FOREIGN KEY (ID_TIPO_ESPECIALIDAD) 
        REFERENCES ESPECIALIDADES(ID_TIPO_ESPECIALIDAD)
);

CREATE TABLE PERSONAL_CARGOS_ESTABLECIMIENTOS (
    ID_PERSONAL_CARGOS_ESTABLECIMIENTOS INT NOT NULL,
    ID_PERSONAL INT NOT NULL,
    ID_CARGO INT NOT NULL,
	ID_ESTABLECIMIENTO INT NOT NULL,
    CONSTRAINT PK_PERSONAL_CARGOS_ESTABLECIMIENTOS PRIMARY KEY (ID_PERSONAL_CARGOS_ESTABLECIMIENTOS),
    CONSTRAINT FK_PERSONAL_CARGOS_ESTABLECIMIENTOS_PERSONAL FOREIGN KEY (ID_PERSONAL) 
        REFERENCES PERSONAL(ID_PERSONAL),
    CONSTRAINT FK_PERSONAL_CARGOS_ESTABLECIMIENTOS_CARGOS FOREIGN KEY (ID_CARGO) 
        REFERENCES CARGOS(ID_CARGO),
	CONSTRAINT FK_PERSONAL_CARGOS_ESTABLECIMIENTOS_ESTABLECIMIENTOS FOREIGN KEY (ID_ESTABLECIMIENTO)
		REFERENCES ESTABLECIMIENTOS(ID_ESTABLECIMIENTO)
);

CREATE TABLE CONTACTOS (
	ID_CONTACTO INT IDENTITY(1,1),
	ID_TIPO_CONTACTO INT NOT NULL,
	ID_PERSONAL INT,
	ID_PROVEEDOR INT,
	ID_LOGISTICA VARCHAR(20),
	ID_ESTABLECIMIENTO INT,
	ID_CLIENTE INT,
	CONTACTO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CONTACTOS PRIMARY KEY (ID_CONTACTO),
	CONSTRAINT FK_CONTACTOS_TIPOS_CONTACTOS FOREIGN KEY (ID_TIPO_CONTACTO)
		REFERENCES TIPOS_CONTACTOS(ID_TIPO_CONTACTO),
	CONSTRAINT FK_CONTACTOS_PERSONAL FOREIGN KEY (ID_PERSONAL)
		REFERENCES PERSONAL(ID_PERSONAL),
	CONSTRAINT FK_CONTACTOS_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR)
		REFERENCES PROVEEDORES(ID_PROVEEDOR),
	CONSTRAINT FK_CONTACTOS_EMPRESA_LOGISTICA FOREIGN KEY (ID_LOGISTICA)
		REFERENCES EMPRESA_LOGISTICA(CUIT)
);



CREATE TABLE FACTURAS (
	ID_FACTURA INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_PERSONAL_CARGOS_ESTABLECIMIENTOS INT,
	FECHA DATE

	CONSTRAINT PK_FACTURAS PRIMARY KEY(ID_FACTURA),
	CONSTRAINT FK_FACTURAS_CLIENTES FOREIGN KEY(ID_CLIENTE)
		REFERENCES CLIENTES(ID_CLIENTE),
	CONSTRAINT FK_FACTURAS_PERSONAL FOREIGN KEY(ID_PERSONAL_CARGOS_ESTABLECIMIENTOS)
		REFERENCES PERSONAL_CARGOS_ESTABLECIMIENTOS(ID_PERSONAL_CARGOS_ESTABLECIMIENTOS)
);


CREATE TABLE DISPENSACIONES(
	ID_FACTURA INT NOT NULL,
	ID_DISPENSACION INT NOT NULL,
	ID_MEDICAMENTO_LOTE INT NULL,
	ID_COBERTURA INT NULL,
	ID_PRODUCTO INT NULL,
	DESCUENTO DECIMAL(10, 2) NULL,
	PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
	CANTIDAD INT NOT NULL,
	MATRICULA VARCHAR(20) NULL,
	CODIGO_VALIDACION VARCHAR(20)

	CONSTRAINT PK_DISPENSACIONES PRIMARY KEY(ID_FACTURA, ID_DISPENSACION),
	CONSTRAINT FK_DISPENSACIONES_FACTURAS FOREIGN KEY(ID_FACTURA)
		REFERENCES FACTURAS(ID_FACTURA),
	CONSTRAINT FK_DISPENSACIONES_MEDICAMENTO_LOTE FOREIGN KEY(ID_MEDICAMENTO_LOTE)
		REFERENCES MEDICAMENTOS_LOTES(ID_MEDICAMENTO_LOTE),
	CONSTRAINT FK_DISPENSACIONES_COBERTURAS FOREIGN KEY(ID_COBERTURA)
		REFERENCES TIPOS_COBERTURAS(ID_TIPO_COBERTURA),
	CONSTRAINT FK_DISPENSACIONES_PRODUCTOS FOREIGN KEY(ID_PRODUCTO)
		REFERENCES PRODUCTOS(ID_PRODUCTO),
	CONSTRAINT FK_DISPENSACIONES_MEDICOS FOREIGN KEY(MATRICULA)
		REFERENCES MEDICOS(MATRICULA)
);


CREATE TABLE FACTURAS_TIPOS_PAGOS(
	ID_FACTURA_TIPO_PAGO INT NOT NULL,
	ID_FACTURA INT NOT NULL,
	ID_TIPO_PAGO INT NULL,
	PORCENTAJE_PAGO DECIMAL(5,2) NULL,
	ES_CUOTAS BIT NULL,
	CANTIDAD_CUOTAS INT NULL

	CONSTRAINT PK_FACT_TIPOS_PAGOS PRIMARY KEY(ID_FACTURA_TIPO_PAGO)
	CONSTRAINT FK_FACT_TIPOS_PAGOS_FACT FOREIGN KEY(ID_FACTURA)
		REFERENCES FACTURAS(ID_FACTURA),
	CONSTRAINT FK_FACT_TIPOS_PAGOS_TIPOS_PAGOS FOREIGN KEY(ID_TIPO_PAGO)
		REFERENCES TIPOS_PAGOS(ID_TIPO_PAGO)
);


CREATE TABLE PEDIDOS(
	ID_PEDIDO INT NOT NULL,
	ID_PERSONAL_CARGOS_ESTABLECIMIENTOS INT NOT NULL,
	ID_LOGISTICA VARCHAR(20) NOT NULL,
	FECHA DATE NOT NULL,
	CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_PEDIDOS_PERSONAL_CARGOS_ESTABLECIMIENTOS FOREIGN KEY (ID_PERSONAL_CARGOS_ESTABLECIMIENTOS)
		REFERENCES PERSONAL_CARGOS_ESTABLECIMIENTOS(ID_PERSONAL_CARGOS_ESTABLECIMIENTOS),
	CONSTRAINT FK_PEDIDOS_EMPRESA_LOGISTICA FOREIGN KEY (ID_LOGISTICA)
		REFERENCES EMPRESA_LOGISTICA(CUIT)
);

CREATE TABLE DETALLES_PEDIDOS(
	ID_PEDIDO INT NOT NULL,
	ID_DETALLE_PEDIDO INT NOT NULL,
	ID_MEDICAMENTO_LOTE INT NULL,
	ID_PROVEEDOR INT NOT NULL,
	ID_PRODUCTO INT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO_UNITARIO DECIMAL (10,2) NOT NULL
	CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (ID_PEDIDO, ID_DETALLE_PEDIDO),
	CONSTRAINT FK_DETALLE_PEDIDO_PEDIDO FOREIGN KEY (ID_PEDIDO)
		REFERENCES PEDIDOS(ID_PEDIDO),
	CONSTRAINT FK_DETALLE_PEDIDO_MEDICAMENTOS_LOTE FOREIGN KEY (ID_MEDICAMENTO_LOTE)
		REFERENCES MEDICAMENTOS_LOTES(ID_MEDICAMENTO_LOTE),
	CONSTRAINT FK_DETALLES_PEDIDOS_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR)
		REFERENCES PROVEEDORES(ID_PROVEEDOR),
	CONSTRAINT FK_DETALLES_PEDIDOS_PRODUCTOS FOREIGN KEY (ID_PRODUCTO)
		REFERENCES PRODUCTOS(ID_PRODUCTO)
);


CREATE TABLE STOCKS(
	ID_STOCK INT,
	FECHA DATE NOT NULL,
	CANTIDAD INT NOT NULL,
	CANTIDAD_MINIMA INT NOT NULL,
	ID_PRODUCTO INT NULL,
	ID_MEDICAMENTO_LOTE INT NULL, 
	ID_ESTABLECIMIENTO INT NOT NULL,
	CONSTRAINT PK_STOCKS PRIMARY KEY (ID_STOCK),
	CONSTRAINT FK_STOCKS_PRODUCTOS FOREIGN KEY (ID_PRODUCTO)
		REFERENCES PRODUCTOS(ID_PRODUCTO),
	CONSTRAINT FK_STOCKS_MEDICAMENTOS_LOTE FOREIGN KEY (ID_MEDICAMENTO_LOTE)
		REFERENCES MEDICAMENTOS_LOTES(ID_MEDICAMENTO_LOTE),
	CONSTRAINT FK_STOCKS_ESTABLECIMIENTOS FOREIGN KEY (ID_ESTABLECIMIENTO)
		REFERENCES ESTABLECIMIENTOS(ID_ESTABLECIMIENTO)
);

CREATE TABLE INVENTARIOS(
	ID_INVENTARIO INT IDENTITY(1,1) NOT NULL,
	ID_FACTURA INT NULL,
	ID_DISPENSACION INT NULL,
	ID_PEDIDO INT NULL,
	ID_DETALLE_PEDIDO INT NULL,
	ID_TIPO_MOV INT NOT NULL,
	ID_STOCK INT NOT NULL,
	CANTIDAD INT NULL,
	FECHA DATE NULL,

	CONSTRAINT PK_INVENTARIOS PRIMARY KEY (ID_INVENTARIO),
	CONSTRAINT FK_INVENTARIO_FACTURAS FOREIGN KEY(ID_FACTURA, ID_DISPENSACION)
		REFERENCES DISPENSACIONES(ID_FACTURA, ID_DISPENSACION),
	CONSTRAINT FK_INVENTARIO_PEDIDOS FOREIGN KEY(ID_PEDIDO, ID_DETALLE_PEDIDO)
		REFERENCES DETALLES_PEDIDOS(ID_PEDIDO, ID_DETALLE_PEDIDO),
	CONSTRAINT FK_INVENTARIOS_TIPOS_MOVIMIENTOS FOREIGN KEY (ID_TIPO_MOV)
		REFERENCES TIPOS_MOVIMIENTOS(ID_TIPO_MOV),
	CONSTRAINT FK_INVENTARIOS_STOCKS FOREIGN KEY (ID_STOCK)
		REFERENCES STOCKS(ID_STOCK)
);


--------------------------------------------------------------------------------------------------
