INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130762,1,2,'1/9/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130796,3,2,'1/9/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130793,1,3,'7/9/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130584,4,3,'4/10/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130810,6,3,'1/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130807,9,11,'3/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(131070,8,11,'10/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130785,1,12,'24/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(32138,1,12,'25/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130186,1,12,'30/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176992,3,2,'10/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(53919,5,3,'13/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176585,5,11,'13/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176320,7,2,'23/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176531,7,2,'30/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176487,3,3,'31/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176519,9,2,'3/2/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176980,9,3,'14/2/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176542,9,2,'24/2/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176626,4,11,'3/3/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132435,3,12,'10/5/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176146,3,2,'12/5/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176935,1,3,'13/5/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(177039,1,3,'20/5/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176809,7,3,'2/6/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176394,6,2,'13/6/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176362,9,11,'21/6/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(177219,9,12,'2/7/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176215,8,12,'29/7/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176995,4,2,'31/7/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176147,5,3,'10/1/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(196150,7,2,'12/1/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(186156,6,3,'14/3/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(116159,8,2,'15/7/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(58175,1,11,'2/8/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176141,3,2,'4/8/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176450,3,3,'2/9/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176274,4,2,'19/9/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176939,9,2,'2/10/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(55102,2,2,'2/10/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176153,5,3,'27/2/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176150,1,2,'28/2/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(196156,3,3,'1/3/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132663,3,3,'12/3/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176145,1,12,'8/4/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(126159,7,11,'26/6/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176138,8,2,'26/6/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(102487,3,12,'20/7/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(146147,5,11,'11/11/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132301,6,12,'11/12/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176749,6,3,'2/1/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132419,7,2,'31/7/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176144,4,12,'2/8/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176156,3,11,'2/8/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132798,1,3,'4/8/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176159,8,2,'11/8/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(116138,9,3,'1/9/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176434,5,11,'12/9/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132487,1,3,'21/9/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176468,3,2,'2/10/2024');								

--------------------------------------------------------FACTURAS TIPOS PAGOS--------------------------------------------------------------------

INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130762,6,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130796,5,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130793,1,80,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130793,2,20,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130584,5,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130810,4,100,1,3);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130807,1,60,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130807,3,40,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),131070,4,100,1,1);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130785,5,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),32138,6,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130186,4,100,1,3);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176992,6,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),53919,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176585,1,50,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176585,6,50,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176320,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176531,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176487,4,100,1,1);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176519,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176980,1,75,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176980,6,25,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176542,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176626,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132435,4,100,1,3);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176146,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176935,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),177039,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176809,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176394,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176362,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),177219,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176215,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176995,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176147,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),196150,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),186156,4,100,1,1);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),116159,4,100,1,1);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),58175,1,60,0,NULL);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),58175,3,40,0,NULL);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176141,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176450,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176274,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176939,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),55102,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176153,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176150,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),196156,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132663,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176145,1,50,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176145,2,50,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),126159,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176138,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),102487,1,40,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),102487,5,60,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),146147,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132301,1,30,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132301,2,70,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176749,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132419,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176144,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176156,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132798,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176159,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),116138,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176434,4,100,1,3);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132487,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176468,1,90,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PROCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176468,2,10,0,NULL);												