INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130762,1,2,'1/9/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130796,3,2,'1/9/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130793,1,3,'7/9/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130584,4,3,'4/10/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130810,6,3,'1/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130807,9,11,'3/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(131070,8,11,'10/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130785,1,12,'24/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(32138,1,12,'25/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(130186,1,12,'30/11/2019');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176992,3,2,'10/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(53919,5,3,'13/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176585,5,11,'13/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176320,7,2,'23/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176531,7,2,'30/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176487,3,3,'31/1/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176519,9,2,'3/2/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176980,9,3,'14/2/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176542,9,2,'24/2/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176626,4,11,'3/3/2020');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132435,3,12,'10/5/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176146,3,2,'12/5/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176935,1,3,'13/5/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(177039,1,3,'20/5/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176809,7,3,'2/6/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176394,6,2,'13/6/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176362,9,11,'21/6/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(177219,9,12,'2/7/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176215,8,12,'29/7/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176995,4,2,'31/7/2021');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176147,5,3,'10/1/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(196150,7,2,'12/1/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(186156,6,3,'14/3/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(116159,8,2,'15/7/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(58175,1,11,'2/8/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176141,3,2,'4/8/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176450,3,3,'2/9/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176274,4,2,'19/9/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176939,9,2,'2/10/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(55102,2,2,'2/10/2022');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176153,5,3,'27/2/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176150,1,2,'28/2/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(196156,3,3,'1/3/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132663,3,3,'12/3/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176145,1,12,'8/4/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(126159,7,11,'26/6/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176138,8,2,'26/6/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(102487,3,12,'20/7/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(146147,5,11,'11/11/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132301,6,12,'11/12/2023');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176749,6,3,'2/1/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132419,7,2,'31/7/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176144,4,12,'2/8/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176156,3,11,'2/8/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132798,1,3,'4/8/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176159,8,2,'11/8/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(116138,9,3,'1/9/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176434,5,11,'12/9/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(132487,1,3,'21/9/2024');								

INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, FECHA)
VALUES(176468,3,2,'2/10/2024');								

--------------------------------------------------------FACTURAS TIPOS PAGOS--------------------------------------------------------------------

INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130762,6,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130796,5,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130793,1,80,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130793,2,20,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130584,5,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130810,4,100,1,3);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130807,1,60,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130807,3,40,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),131070,4,100,1,1);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130785,5,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),32138,6,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),130186,4,100,1,3);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176992,6,100,0,NULL);
												
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),53919,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176585,1,50,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176585,6,50,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176320,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176531,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176487,4,100,1,1);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176519,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176980,1,75,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176980,6,25,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176542,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176626,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132435,4,100,1,3);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176146,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176935,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),177039,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176809,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176394,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176362,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),177219,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176215,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176995,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176147,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),196150,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),186156,4,100,1,1);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),116159,4,100,1,1);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),58175,1,60,0,NULL);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),58175,3,40,0,NULL);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176141,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176450,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176274,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176939,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),55102,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176153,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176150,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),196156,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132663,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176145,1,50,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176145,2,50,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),126159,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176138,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),102487,1,40,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),102487,5,60,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),146147,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132301,1,30,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132301,2,70,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176749,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132419,5,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176144,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176156,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132798,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176159,3,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),116138,6,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176434,4,100,1,3);		
										
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),132487,2,100,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176468,1,90,0,NULL);	
											
INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
VALUES((SELECT MAX(ID_FACTURA_TIPO_PAGO)+ 1 FROM FACTURAS_TIPOS_PAGOS ),176468,2,10,0,NULL);												

-----------------------------------------------------------DISPENSACIONES-----------------------------------------------------------------------------
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130762,1,75,16,NULL,0.15,32.85,60,'AB123CD','OZEK6838');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130796,1,155,13,NULL,0.2,85.36,30,'DF789RT','MECM2440');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130796,2,9,13,NULL,0.2,51.83,30,'DF789RT','MECM2440');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130793,1,48,12,NULL,0.6,4628.04,1,'LK321OP','EECQ5982');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130793,2,42,12,NULL,0.6,976.82,2,'LK321OP','EECQ5982');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130584,1,NULL,NULL,5,0,200,2,NULL,NULL);					
							
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130584,2,NULL,NULL,8,0,3000,1,NULL,NULL);		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130810,1,136,3,NULL,0.3,29.87,10,'DF789RT','ACTQ3825');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130810,2,75,3,NULL,0.3,32.85,60,'DF789RT','ACTQ3825');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130807,1,120,19,NULL,0.3,112.86,60,'LK321OP','OMQT8821');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130807,2,115,19,NULL,0.3,94.67,60,'LK321OP','OMQT8821');	
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130807,3,89,19,NULL,0.3,156.26,30,'LK321OP','OMQT8821');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(131070,1,120,20,NULL,0,112.86,60,'DF789RT','EKQM9712');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(131070,2,75,20,NULL,0.2,32.85,60,'DF789RT','EKQM9712');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130785,1,41,7,NULL,0.25,1096.5,1,'QQW4431','EEQF4777');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(32138,1,129,11,NULL,0.3,1713.94,1,'WE234MN','OMCZ7313');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130186,1,36,20,NULL,0,187.76,30,'QQW4431','FAAT4614');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(130186,2,74,20,NULL,0,32.85,60,'QQW4431','FAAT4614');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176992,1,89,6,NULL,0.15,265.15,30,'AS987TY','KFMT3190');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176992,2,75,6,NULL,0.15,121.74,60,'AS987TY','KFMT3190');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(53919,1,110,2,NULL,0.25,149.75,10,'MN654QW','QEEE6184');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(53919,2,59,2,NULL,0.25,492.89,16,'MN654QW','QEEE6184');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(53919,3,48,2,NULL,0.25,8516.49,1,'MN654QW','QEEE6184');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176585,1,95,6,NULL,0.15,2940,1,'JK789ZX','MZMQ2050');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176585,2,69,6,NULL,0.15,3502,1,'JK789ZX','MZMQ2050');	
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176320,1,59,3,NULL,0.3,492.89,16,'19882fc','ACFQ7650');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176320,2,29,3,NULL,0.3,141,20,'19882fc','ACFQ7650');			
									
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176531,1,137,19,NULL,0.3,2491.56,1,'1982A1c','CTOQ4653');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176531,2,168,19,NULL,0.3,3103.3,1,'1982A1c','CTOQ4653');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176531,3,65,19,NULL,0.3,3701.99,1,'1982A1c','CTOQ4653');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176531,4,92,19,NULL,0.3,3716.37,1,'1982A1c','CTOQ4653');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176487,1,54,14,NULL,0.3,311.31,16,'QQW4431','AZCA2475');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176487,2,95,14,NULL,0.3,2940,2,'QQW4431','AZCA2475');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176487,3,96,14,NULL,0.3,93.15,10,'QQW4431','AZCA2475');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176519,1,120,13,NULL,0.2,202.79,60,'LK321OP','KZOQ8285');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176519,2,74,13,NULL,0.2,121.74,30,'LK321OP','KZOQ8285');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176519,3,108,13,NULL,0.2,91.05,50,'LK321OP','KZOQ8285');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176980,1,114,17,NULL,0.1,171.18,30,'GH123CV','COTT3958');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176542,1,16,14,NULL,0.3,151.28,60,'LK321OP','TQOQ1481');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176542,2,110,14,NULL,0.3,149.75,10,'LK321OP','TQOQ1481');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176542,3,115,14,NULL,0.3,155.61,60,'LK321OP','TQOQ1481');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176626,1,NULL,NULL,13,0,400,10,NULL,NULL);				
								
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176626,2,NULL,NULL,16,0,700,2,NULL,NULL);				
								
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132435,1,170,7,NULL,0.25,215.21,30,'UY567OP','FEAZ8262');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176146,1,103,7,NULL,0.25,690.14,30,'RT456YU','OCZE2538');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176146,2,170,7,NULL,0.25,215.21,30,'RT456YU','OCZE2538');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176146,3,73,7,NULL,0.25,747.54,60,'RT456YU','OCZE2538');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176146,4,63,7,NULL,0.25,106.26,30,'RT456YU','OCZE2538');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176935,1,130,17,NULL,0.1,980.29,6,'RT456YU','MEFQ9748');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(177039,1,125,18,NULL,0.2,3825,1,'QP123AS','CZQC2359');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(177039,2,136,18,NULL,0.2,70.16,10,'QP123AS','CZQC2359');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176809,1,95,3,NULL,0.3,2940,1,'UY567OP','QZMO9770');			
									
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176809,2,69,3,NULL,0.3,3502,1,'UY567OP','QZMO9770');			
									
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176394,1,41,11,NULL,0.3,1181.5,1,'MN654QW','OZAF1468');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176362,1,161,5,NULL,0.1,3274.2,1,'XY987ZY','KTTA8129');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176362,2,95,5,NULL,0.1,2940,1,'XY987ZY','KTTA8129');			
									
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(177219,1,29,4,NULL,0.35,141,10,'QP123AS','MCTE8453');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(177219,2,136,4,NULL,0.35,70.16,10,'QP123AS','MCTE8453');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176215,1,75,20,NULL,0,121.74,60,'AB123CD','MZME3671');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176215,2,134,20,NULL,0,103.08,14,'AB123CD','MZME3671');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176215,3,154,20,NULL,0,5873.76,1,'AB123CD','MZME3671');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176995,1,NULL,NULL,2,0,1500,2,NULL,NULL);					
							
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(146147,1,9,7,NULL,0.25,117.31,60,'ZX987CV','AKFO8808');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(146147,2,81,7,NULL,0.25,69.34,30,'ZX987CV','AKFO8808');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(146147,3,64,7,NULL,0.25,413.9,30,'ZX987CV','AKFO8808');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(196150,1,106,12,NULL,0.6,83.25,30,'RT456YU','MZOE4897');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(196150,2,140,12,NULL,0.6,276.48,30,'RT456YU','MZOE4897');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(186156,1,63,4,NULL,0.35,106.26,30,'QQW4431','OOKM2222');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(186156,2,148,4,NULL,0.35,361.91,60,'QQW4431','OOKM2222');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(186156,3,14,4,NULL,0.35,139.95,60,'QQW4431','OOKM2222');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(116159,1,106,20,NULL,0,83.25,30,'RT456YU','OQOQ1138');			
									
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(116159,2,148,20,NULL,0,361.91,60,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(116159,3,150,20,NULL,0,105.95,60,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(116159,4,113,20,NULL,0,48.15,30,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(58175,1,97,5,NULL,0.1,1798.01,1,'LK321OP','KAFQ8523');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176141,1,106,9,NULL,0.15,88.45,30,'QQW4431','CMMF7606');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176141,2,103,9,NULL,0.15,759.15,30,'QQW4431','CMMF7606');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176141,3,113,9,NULL,0.15,57.23,30,'QQW4431','CMMF7606');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176141,4,167,9,NULL,0.15,268.72,30,'QQW4431','CMMF7606');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176450,1,75,3,NULL,0.3,121.74,60,'DF789RT','AMAO2072');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176274,1,NULL,NULL,10,0,300,2,NULL,NULL);				
								
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176274,2,NULL,NULL,7,0,5000,1,NULL,NULL);				
								
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176274,3,NULL,NULL,4,0,10700,1,NULL,NULL);				
								
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176274,4,NULL,NULL,1,0,1100,2,NULL,NULL);				
								
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176939,1,75,5,NULL,0.1,121.74,60,'WE234MN','CAKT2474');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(55102,1,75,14,NULL,0.3,121.74,60,'GH123CV','QQZZZZZZZZZ6211');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(55102,2,89,14,NULL,0.3,265.15,30,'GH123CV','QQZZZZZZZZZ6211');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176153,1,106,7,NULL,0.25,83.25,30,'WE234MN','EAAQ3729');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176153,2,9,7,NULL,0.25,117.31,60,'WE234MN','EAAQ3729');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176153,3,155,7,NULL,0.25,145.04,60,'WE234MN','EAAQ3729');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176150,1,106,12,NULL,0.6,83.25,30,'RT456YU','MZOE4897');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176150,2,140,12,NULL,0.6,276.48,30,'RT456YU','MZOE4897');
												
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(196156,1,63,4,NULL,0.35,106.26,30,'QQW4431','OOKM2222');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(196156,2,148,4,NULL,0.35,361.91,60,'QQW4431','OOKM2222');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(196156,3,14,4,NULL,0.35,139.95,60,'QQW4431','OOKM2222');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132663,1,154,10,NULL,0.25,5873.76,1,'LO456UI','KMOK8196');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132663,2,48,10,NULL,0.25,8516.49,1,'LO456UI','KMOK8196');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176145,1,103,7,NULL,0.25,690.14,30,'RT456YU','OCZE2538');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176145,2,170,7,NULL,0.25,215.21,30,'RT456YU','OCZE2538');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176145,3,73,7,NULL,0.25,747.54,60,'RT456YU','OCZE2538');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176145,4,63,7,NULL,0.25,106.26,30,'RT456YU','OCZE2538');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(126159,1,106,20,NULL,0,83.25,30,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(126159,2,148,20,NULL,0,361.91,60,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(126159,3,150,20,NULL,0,105.95,60,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(126159,4,113,20,NULL,0,48.15,30,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(116138,1,170,20,NULL,0,215.21,30,'DF789RT','OKTT9196');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(116138,2,63,20,NULL,0,106.26,30,'DF789RT','OKTT9196');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(116138,3,155,20,NULL,0,145.04,30,'DF789RT','OKTT9196');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(102487,1,170,14,NULL,0.3,215.21,30,'ZX567FG','MEEO2649');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(102487,2,140,14,NULL,0.3,276.48,30,'ZX567FG','MEEO2649');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(102487,3,151,14,NULL,0.3,172.03,30,'ZX567FG','MEEO2649');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176147,1,9,7,NULL,0.25,117.31,60,'ZX987CV','AKFO8808');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176147,2,81,7,NULL,0.25,69.34,30,'ZX987CV','AKFO8808');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176147,3,64,7,NULL,0.25,413.9,30,'ZX987CV','AKFO8808');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132301,1,74,19,NULL,0.3,133.91,30,'HJ234LK','COOM2264');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176749,1,110,16,NULL,0.15,149.75,30,'WE234MN','QCTQ2104');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132419,1,155,7,NULL,0.25,145.04,60,'RT456YU','TETT6721');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176144,1,NULL,NULL,11,0,10000,1,NULL,NULL);					
							
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176144,2,NULL,NULL,16,0,3800,1,NULL,NULL);					
							
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176144,3,NULL,NULL,3,0,6150,1,NULL,NULL);					
							
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176144,4,NULL,NULL,5,0,2120,2,NULL,NULL);					
							
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176156,1,63,4,NULL,0.35,106.26,30,'QQW4431','OOKM2222');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176156,2,148,4,NULL,0.35,361.91,60,'QQW4431','OOKM2222');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176156,3,14,4,NULL,0.35,139.95,60,'QQW4431','OOKM2222');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132798,1,108,14,NULL,0.3,125.42,50,'XY987ZY','KEKA6259');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132798,2,107,14,NULL,0.3,261.76,50,'XY987ZY','KEKA6259');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132798,3,74,17,NULL,0.1,121.74,30,'XY987ZY','KEKA6259');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176159,1,106,20,NULL,0,83.25,30,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176159,2,148,20,NULL,0,361.91,60,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176159,3,150,20,NULL,0,105.95,60,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176159,4,113,20,NULL,0,48.15,30,'RT456YU','OQOQ1138');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176138,1,170,20,NULL,0,215.21,30,'DF789RT','OKTT9196');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176138,2,63,20,NULL,0,106.26,30,'DF789RT','OKTT9196');			
									
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176138,3,155,20,NULL,0,145.04,30,'DF789RT','OKTT9196');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176434,1,130,9,NULL,0.15,980.29,6,'AS987TY','FFCK3210');		
										
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132487,1,170,14,NULL,0.3,215.21,30,'ZX567FG','MEEO2649');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132487,2,140,14,NULL,0.3,276.48,30,'ZX567FG','MEEO2649');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(132487,3,151,14,NULL,0.3,172.03,30,'ZX567FG','MEEO2649');	
											
INSERT INTO DISPENSACIONES(ID_FACTURA, ID_DISPENSACION, ID_MEDICAMENTO_LOTE, ID_COBERTURA, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(176468,1,29,5,NULL,0.1,141,10,'AB123CD','MAZQ4399');		


------------------------------------------------------------------ CONSULTAS ---------------------------------------------------------------------------

SELECT F.ID_FACTURA 'NUMERO DE FACTURA',
	   YEAR(F.FECHA) 'AÑO',
	   COUNT(D.ID_DISPENSACION) 'CANTIDAD DISPENSACIONES',	   
	   'CREDITO' 'TIPO PAGO'
FROM FACTURAS F
JOIN FACTURAS_TIPOS_PAGOS FTP ON FTP.ID_FACTURA = F.ID_FACTURA
JOIN TIPOS_PAGOS TP ON TP.ID_TIPO_PAGO = FTP.ID_TIPO_PAGO
JOIN DISPENSACIONES D ON D.ID_FACTURA = F.ID_FACTURA
WHERE TP.TIPO_PAGO = 'Tarjeta de Credito'
GROUP BY YEAR(F.FECHA), F.ID_FACTURA
HAVING 2 < (SELECT COUNT(*) FROM DISPENSACIONES DI WHERE DI.ID_FACTURA = F.ID_FACTURA)

UNION 

SELECT F.ID_FACTURA,
	   YEAR(F.FECHA) 'AÑO',
	   COUNT(D.ID_DISPENSACION),
	   'QR_MODO'
FROM FACTURAS F
JOIN FACTURAS_TIPOS_PAGOS FTP ON FTP.ID_FACTURA = F.ID_FACTURA
JOIN TIPOS_PAGOS TP ON TP.ID_TIPO_PAGO = FTP.ID_TIPO_PAGO
JOIN DISPENSACIONES D ON D.ID_FACTURA = F.ID_FACTURA
WHERE TP.TIPO_PAGO = 'QR MODO'
GROUP BY YEAR(F.FECHA), F.ID_FACTURA
HAVING 5000 <  ALL (SELECT D1.CANTIDAD*(D1.PRECIO_UNITARIO-(D1.DESCUENTO*D1.PRECIO_UNITARIO)) FROM DISPENSACIONES D1 WHERE D1.ID_FACTURA = F.ID_FACTURA)
																																	