
-- INICIO TEST TRIGGER DIS_VERIFICAR_STOCK_VENTA
INSERT INTO DISPENSACIONES(ID_DISPENSACION, ID_FACTURA, ID_MEDICAMENTO_LOTE, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
VALUES(234234, 1, NULL, 5, 0, 2220, 2, NULL, NULL)


	--establecimiento 2
	--producto 5
	-- FUNCIONA PRODUCTOS si no tiene stock tira el error y si no, inserta bien


INSERT INTO DISPENSACIONES(ID_DISPENSACION,ID_FACTURA,ID_MEDICAMENTO_LOTE, ID_COBERTURA, DESCUENTO,PRECIO_UNITARIO,CANTIDAD,MATRICULA,CODIGO_VALIDACION)
	VALUES(2323,2,3,1,0.20,855.54,2,'AB123CD','JCKI4902')

	-- establecimiento 4
	-- medicamento 3
	-- FUNCIONA MEDICAMENTOS si no tiene stock tira el error y si no, inserta bien

--- FIN TEST TRIGGER DIS_VERIFICAR_STOCK_VENTA




-- INICIO TEST TRIGGER INVENTARIO

-- PRODUCTO

INSERT INTO DISPENSACIONES(ID_DISPENSACION, ID_FACTURA, ID_MEDICAMENTO_LOTE, ID_PRODUCTO, DESCUENTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
		VALUES(6, 1, NULL, 5, 0, 2220, 2, NULL, NULL)


-- MEDICAMTENTO

INSERT INTO DISPENSACIONES(ID_DISPENSACION,ID_FACTURA,ID_MEDICAMENTO_LOTE, ID_COBERTURA, DESCUENTO,PRECIO_UNITARIO,CANTIDAD,MATRICULA,CODIGO_VALIDACION)
	VALUES(3,2,3,1,0.20,855.54,6,'AB123CD','JCKI4902')

-- FIN TEST TRIGGER INVENTARIO


-- INICIO TEST DIS_ACTUALIZAR_STOCK_OTROS

INSERT INTO INVENTARIOS(ID_FACTURA, ID_DISPENSACION , ID_TIPO_MOV, ID_STOCK, CANTIDAD)
			VALUES( null, null, 3,  107, 100)

-- FIN TEST DIS_ACTUALIZAR_STOCK_OTROS


-- INICIO TEST TRIGGER DIS_REPONER_ARTICULO

--Se debe tener en cuenta la posibilidad de que el establecimiento tenga o no previamente 
--un registro de stock cargado; según eso, procederá a crear uno o usar el ya existente
INSERT INTO DETALLES_PEDIDOS(ID_PEDIDO,ID_DETALLE_PEDIDO,ID_MEDICAMENTO_LOTE,ID_PROVEEDOR,ID_PRODUCTO,CANTIDAD,PRECIO_UNITARIO)
VALUES (4,19,3,10,NULL,1000,3500)

--Para el seguimiento de valores insertados al pedido con id_pedido = 4
SELECT * FROM DETALLES_PEDIDOS --27
SELECT * FROM INVENTARIOS
WHERE ID_PEDIDO = 4 --18
SELECT * FROM STOCKS
WHERE ID_ESTABLECIMIENTO = 3 --20
-- FIN TEST TRIGGER DIS_REPONER_ARTICULO
