	


------------------------------------------------------------------ CONSULTAS ---------------------------------------------------------------------------
-- Esta consulta es casi lo mismo que la 2. Hay que cambiarla
SELECT F.ID_FACTURA 'NUMERO DE FACTURA',
	   YEAR(F.FECHA) 'AÑO',
	   COUNT(D.ID_DISPENSACION) 'CANTIDAD DISPENSACIONES',	   
	   'CREDITO' 'TIPO PAGO'
FROM FACTURAS F
JOIN FACTURAS_TIPOS_PAGOS FTP ON FTP.ID_FACTURA = F.ID_FACTURA
JOIN TIPOS_PAGOS TP ON TP.ID_TIPO_PAGO = FTP.ID_TIPO_PAGO
JOIN DISPENSACIONES D ON D.ID_FACTURA = F.ID_FACTURA
WHERE TP.TIPO_PAGO = 'Tarjeta de Credito'
GROUP BY YEAR(F.FECHA), F.ID_FACTURA
HAVING 2 < (SELECT COUNT(*) FROM DISPENSACIONES DI WHERE DI.ID_FACTURA = F.ID_FACTURA)

UNION 

SELECT F.ID_FACTURA,
	   YEAR(F.FECHA) 'AÑO',
	   COUNT(D.ID_DISPENSACION),
	   'QR_MODO'
FROM FACTURAS F
JOIN FACTURAS_TIPOS_PAGOS FTP ON FTP.ID_FACTURA = F.ID_FACTURA
JOIN TIPOS_PAGOS TP ON TP.ID_TIPO_PAGO = FTP.ID_TIPO_PAGO
JOIN DISPENSACIONES D ON D.ID_FACTURA = F.ID_FACTURA
WHERE TP.TIPO_PAGO = 'QR MODO'
GROUP BY YEAR(F.FECHA), F.ID_FACTURA
HAVING 5000 <  ALL (SELECT D1.CANTIDAD*(D1.PRECIO_UNITARIO-(D1.DESCUENTO*D1.PRECIO_UNITARIO)) FROM DISPENSACIONES D1 WHERE D1.ID_FACTURA = F.ID_FACTURA)



--1)
--Mostrar los totales facturados por año, mes y vendedor, además de la venta mas cara, siempre y cuando este total sea superior a su propio promedio
-- de ventas en el año corriente.
select YEAR(F.FECHA) 'AÑO', 
	   MONTH(F.FECHA) 'MES',
	   F.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS 'ID_PERSONAL',
	   P.APELLIDO + ', ' + P.NOMBRE 'PERSONAL',
	   SUM(D.CANTIDAD * D.PRECIO_UNITARIO) 'TOTAL_FACTURADO',
	   MAX(D.CANTIDAD*D.PRECIO_UNITARIO) 'VENTA_MAS_CARA'
From FACTURAS F
JOIN PERSONAL_CARGOS_ESTABLECIMIENTOS PCE ON PCE.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS =  F.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS
JOIN DISPENSACIONES D ON D.ID_FACTURA = F.ID_FACTURA
JOIN PERSONAL P ON P.ID_PERSONAL = PCE.ID_PERSONAL
GROUP BY YEAR(F.FECHA), MONTH(F.FECHA), P.APELLIDO + ', ' + P.NOMBRE, F.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS
HAVING SUM(D.CANTIDAD * D.PRECIO_UNITARIO) < (SELECT SBC.PROMEDIO
												FROM (SELECT F1.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS 'ID_PERSONAL_1', AVG(D1.CANTIDAD*(D1.PRECIO_UNITARIO-(D1.DESCUENTO*D1.PRECIO_UNITARIO))) 'PROMEDIO'
													  FROM FACTURAS F1
													  JOIN DISPENSACIONES D1 ON D1.ID_FACTURA = F1.ID_FACTURA
													  WHERE YEAR(F1.FECHA) = YEAR(GETDATE())
													  GROUP BY F1.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS
													  ) AS SBC
												WHERE SBC.ID_PERSONAL_1 = F.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS)

--2)
-- Se necesita saber la cantidad de clientes que pagaron al menos dos productos diferentes segun tipo de pago, 
 
SELECT YEAR(F.FECHA) 'AÑO',
	   COUNT(F.ID_FACTURA) 'CANTIDAD_FACTURAS',
	   'Tarjeta de Credito' 'TIPO_PAGO'
FROM FACTURAS F
JOIN FACTURAS_TIPOS_PAGOS FTP ON FTP.ID_FACTURA = F.ID_FACTURA
JOIN TIPOS_PAGOS TP ON TP.ID_TIPO_PAGO = FTP.ID_TIPO_PAGO
JOIN (SELECT F1.ID_FACTURA 'FACTURA', COUNT(D1.ID_FACTURA) 'CANTIDAD_DETALLES'
	  FROM FACTURAS F1
	  JOIN DISPENSACIONES D1 ON D1.ID_FACTURA = F1.ID_FACTURA
	  GROUP BY F1.ID_FACTURA) SC ON SC.FACTURA = F.ID_FACTURA
WHERE TP.TIPO_PAGO = 'Tarjeta de Credito'
AND SC.CANTIDAD_DETALLES > 2
GROUP BY YEAR(F.FECHA)

UNION

SELECT YEAR(F.FECHA) 'AÑO',
	   COUNT(F.ID_FACTURA) 'CANTIDAD_FACTURAS',
	   'QR_MODO'
FROM FACTURAS F
JOIN FACTURAS_TIPOS_PAGOS FTP ON FTP.ID_FACTURA = F.ID_FACTURA
JOIN TIPOS_PAGOS TP ON TP.ID_TIPO_PAGO = FTP.ID_TIPO_PAGO
WHERE TP.TIPO_PAGO = 'QR MODO'
GROUP BY YEAR(F.FECHA)

UNION

SELECT YEAR(F.FECHA) 'AÑO',
	   COUNT(F.ID_FACTURA) 'CANTIDAD_FACTURAS',
	   'Transferencia'
FROM FACTURAS F
JOIN FACTURAS_TIPOS_PAGOS FTP ON FTP.ID_FACTURA = F.ID_FACTURA
JOIN TIPOS_PAGOS TP ON TP.ID_TIPO_PAGO = FTP.ID_TIPO_PAGO
WHERE TP.TIPO_PAGO = 'Transferencia'
GROUP BY YEAR(F.FECHA)

ORDER BY 3



--3)								
--- Se quiere saber el total facturado por cada establecimiento desde el comienzo de los registros, el mejor año y su facturacion tomando
--- en cuenta únicamente las ventas de medicamentos.

select E.ID_ESTABLECIMIENTO,e.NOMBRE 'Establecimiento', FORMAT(SUM(d.CANTIDAD * (d.PRECIO_UNITARIO - (d.PRECIO_UNITARIO * d.DESCUENTO))), 'N2') 'Total facturado'
		,(select '$' + FORMAT(SCMA.Facturado, 'N2') + ', año ' + CAST(SCMA.Año AS VARCHAR(5)) from

				(select top 1 year(f.FECHA) 'Año' , e1.NOMBRE, SUM(d.CANTIDAD * (d.PRECIO_UNITARIO - (d.PRECIO_UNITARIO * d.DESCUENTO))) 'Facturado'  from FACTURAS f 	
					join DISPENSACIONES d on f.ID_FACTURA = d.ID_FACTURA
					join PERSONAL_CARGOS_ESTABLECIMIENTOS pce on f.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS = pce.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS
					join ESTABLECIMIENTOS e1 on pce.ID_ESTABLECIMIENTO = e.ID_ESTABLECIMIENTO
					where e1.ID_ESTABLECIMIENTO = e.ID_ESTABLECIMIENTO
						and d.ID_MEDICAMENTO_LOTE is not null
					group by year(f.FECHA), e1.NOMBRE		
					order by 3 desc) as SCMA) 'Mejor año facturado' from FACTURAS f

		join DISPENSACIONES d on f.ID_FACTURA = d.ID_FACTURA
		join PERSONAL_CARGOS_ESTABLECIMIENTOS pce on f.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS = pce.ID_PERSONAL_CARGOS_ESTABLECIMIENTOS
		join ESTABLECIMIENTOS e on pce.ID_ESTABLECIMIENTO = e.ID_ESTABLECIMIENTO
		where d.ID_MEDICAMENTO_LOTE is not null	
		group by  E.ID_ESTABLECIMIENTO, e.NOMBRE					


--4)
--Listar clientes con su contacto y barrio, la cantidad de compras del mes 
--y su mayor monto de compra.
--Además, estos clientes deben ser los que tuvieron la mayor cantidad de medicamentos dispensados cada mes
-- y que su mayor monto de compra (de dicho mes) sea mayor al promedio general de montos de compra.
--Agrupar por mes, ordenado por el total de medicamentos dispensados.
SELECT 
    YEAR(F.FECHA) AS anio,  
    DATENAME(MONTH, F.FECHA) AS mes, 
    C.NOMBRE + ' ' + C.APELLIDO AS cliente, 
    SUM(CASE WHEN D.ID_MEDICAMENTO_LOTE IS NOT NULL THEN D.CANTIDAD ELSE 0 END) AS total_medicamentos,
    CO.CONTACTO, 
    B.BARRIO, 
    COUNT(*) AS cantidad_compras, 
    MAX(D.CANTIDAD * (D.PRECIO_UNITARIO - (D.PRECIO_UNITARIO * D.DESCUENTO))) AS mayor_monto 
FROM 
    DISPENSACIONES D
JOIN 
    FACTURAS F ON F.ID_FACTURA = D.ID_FACTURA
JOIN 
    CLIENTES C ON F.ID_CLIENTE = C.ID_CLIENTE
JOIN 
    CONTACTOS CO ON CO.ID_CLIENTE = C.ID_CLIENTE
JOIN 
    BARRIOS B ON B.ID_BARRIO = C.ID_BARRIO
JOIN 
    MEDICAMENTOS_LOTES ML ON ML.ID_MEDICAMENTO_LOTE = D.ID_MEDICAMENTO_LOTE
JOIN 
    MEDICAMENTOS M ON M.ID_MEDICAMENTO = ML.ID_MEDICAMENTO
GROUP BY 
    YEAR(F.FECHA), 
    DATENAME(MONTH, F.FECHA), 
    C.NOMBRE + ' ' + C.APELLIDO, 
    CO.CONTACTO, 
    B.BARRIO
HAVING 
    MAX(D.CANTIDAD * (D.PRECIO_UNITARIO - (D.PRECIO_UNITARIO * D.DESCUENTO))) > 
    (SELECT AVG(D1.CANTIDAD * (D1.PRECIO_UNITARIO - (D1.PRECIO_UNITARIO * D1.DESCUENTO))) 
     FROM DISPENSACIONES D1) 
ORDER BY 
    total_medicamentos DESC;






