-- 2da entrega Nacho
--FACTURAS ok
INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS,FECHA)
			VALUES(10, 9, 2, '04-08-2024');
--FACTURAS_TIPOS_PAGOS ok
INSERT INTO FACTURAS_TIPOS_PAGOS (ID_FACTURA_TIPO_PAGO,ID_FACTURA,ID_TIPO_PAGO,PORCENTAJE_PAGO,ES_CUOTAS,CANTIDAD_CUOTAS)
	VALUES(11, 10, 6, 50, 0, null);
INSERT INTO FACTURAS_TIPOS_PAGOS (ID_FACTURA_TIPO_PAGO,ID_FACTURA,ID_TIPO_PAGO,PORCENTAJE_PAGO,ES_CUOTAS,CANTIDAD_CUOTAS)
	VALUES(12, 10, 1, 50, 1, 3);
--DISPENSACIONES ok
INSERT INTO DISPENSACIONES(ID_DISPENSACION,ID_FACTURA,ID_MEDICAMENTO_LOTE, ID_COBERTURA, DESCUENTO,PRECIO_UNITARIO,CANTIDAD,MATRICULA,CODIGO_VALIDACION)
	VALUES (1, 10, NULL, 9, NULL, 8000, 1, NULL, NULL);
INSERT INTO DISPENSACIONES(ID_DISPENSACION,ID_FACTURA,ID_MEDICAMENTO_LOTE, ID_COBERTURA, DESCUENTO,PRECIO_UNITARIO,CANTIDAD,MATRICULA,CODIGO_VALIDACION)
	VALUES (2, 10, NULL, 5, NULL, 2220, 2, NULL, NULL);
INSERT INTO DISPENSACIONES(ID_DISPENSACION,ID_FACTURA,ID_MEDICAMENTO_LOTE, ID_COBERTURA, DESCUENTO,PRECIO_UNITARIO,CANTIDAD,MATRICULA,CODIGO_VALIDACION)
	VALUES (3, 10, NULL, 10, NULL, 800, 4, NULL, NULL);
--INVENTARIOS DE FACTURAS OK
INSERT INTO INVENTARIOS(ID_INVENTARIO, ID_FACTURA, ID_DISPENSACION, ID_TIPO_MOV, ID_STOCK)
	VALUES (20, 10, 1, 2, 58);
INSERT INTO INVENTARIOS(ID_INVENTARIO, ID_FACTURA, ID_DISPENSACION, ID_TIPO_MOV, ID_STOCK)
	VALUES (21, 10, 2, 2, 31);
INSERT INTO INVENTARIOS(ID_INVENTARIO, ID_FACTURA, ID_DISPENSACION, ID_TIPO_MOV, ID_STOCK)
	VALUES (22, 10, 3, 2, 65);

--PEDIDOS OK
INSERT INTO PEDIDOS(ID_PEDIDO, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, ID_LOGISTICA, FECHA)
		VALUES(5, 2, '20354125877', '01-08-2024')
--DETALLES_PEDIDOS OK
INSERT INTO DETALLES_PEDIDOS(ID_DETALLE_PEDIDO, ID_PEDIDO, ID_MEDICAMENTO_LOTE, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
			VALUES(1, 5, 20, 2, NULL, 10, 454.37)
INSERT INTO DETALLES_PEDIDOS(ID_DETALLE_PEDIDO, ID_PEDIDO, ID_MEDICAMENTO_LOTE, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
			VALUES(2, 5, 21, 2, NULL, 15, 10252.77)
INSERT INTO DETALLES_PEDIDOS(ID_DETALLE_PEDIDO, ID_PEDIDO, ID_MEDICAMENTO_LOTE, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
			VALUES(3, 5, 22, 2, NULL, 15, 4921.50)
INSERT INTO DETALLES_PEDIDOS(ID_DETALLE_PEDIDO, ID_PEDIDO, ID_MEDICAMENTO_LOTE, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
			VALUES(4, 5, 23, 2, NULL, 30, 6281.50)
--INVENTARIOS DE PEDIDOS
INSERT INTO INVENTARIOS(ID_INVENTARIO, ID_PEDIDO, ID_DETALLE_PEDIDO, FECHA, ID_TIPO_MOV, ID_STOCK)
	VALUES (26, 5, 1, 2, 58);
INSERT INTO INVENTARIOS(ID_INVENTARIO, ID_PEDIDO, ID_DETALLE_PEDIDO, FECHA, ID_TIPO_MOV, ID_STOCK)
	VALUES (27, 5, 1, 2, 58);
INSERT INTO INVENTARIOS(ID_INVENTARIO, ID_PEDIDO, ID_DETALLE_PEDIDO, FECHA, ID_TIPO_MOV, ID_STOCK)
	VALUES (28, 5, 1, 2, 58);
INSERT INTO INVENTARIOS(ID_INVENTARIO, ID_PEDIDO, ID_DETALLE_PEDIDO, FECHA, ID_TIPO_MOV, ID_STOCK)
	VALUES (29, 5, 1, 2, 58);


SELECT * FROM MEDICAMENTOS
SELECT * FROM MEDICAMENTOS_LOTES
SELECT * FROM INVENTARIOS