
set dateformat dmy

---
---- FACTURA
INSERT INTO FACTURAS(ID_FACTURA, ID_CLIENTE, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS,FECHA)
			VALUES(1, 3, 2, '03-08-2024');

----
----- FACTURA TIPO PAGO

INSERT INTO FACTURAS_TIPOS_PAGOS(ID_FACTURA_TIPO_PAGO, ID_FACTURA, ID_TIPO_PAGO, PORCENTAJE_PAGO, ES_CUOTAS, CANTIDAD_CUOTAS)
			VALUES(1, 1, 2, 100, 0, NULL)

----
------ DETALLES FACTURA
INSERT INTO DISPENSACIONES(ID_DISPENSACION, ID_FACTURA, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PRODUCTO, DESCUENTO_PRODUCTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
		VALUES(1, 1, NULL, 5, NULL, 2220, 2, NULL, NULL)

INSERT INTO DISPENSACIONES(ID_DISPENSACION, ID_FACTURA, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PRODUCTO, DESCUENTO_PRODUCTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
		VALUES(2, 1, NULL, 6, NULL, 7050, 4, NULL, NULL)
INSERT INTO DISPENSACIONES(ID_DISPENSACION, ID_FACTURA, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PRODUCTO, DESCUENTO_PRODUCTO, PRECIO_UNITARIO, CANTIDAD, MATRICULA, CODIGO_VALIDACION)
		VALUES(3, 1, NULL, 16, NULL, 4200, 1, NULL, NULL)


---
---- INVENTARIO FACTURA

INSERT INTO INVENTARIOS(ID_INVENTARIO, CANTIDAD, FECHA, ID_TIPO_MOV, ID_STOCK)
			VALUES(1, 2, '03-08-2024', 2,  31)
INSERT INTO INVENTARIOS(ID_INVENTARIO, CANTIDAD, FECHA, ID_TIPO_MOV, ID_STOCK)
			VALUES(2, 4, '03-08-2024', 2,  37)
INSERT INTO INVENTARIOS(ID_INVENTARIO, CANTIDAD, FECHA, ID_TIPO_MOV, ID_STOCK)
			VALUES(3, 1, '03-08-2024', 2,  107)


---
---- PEDIDOS

INSERT INTO PEDIDOS(ID_PEDIDO, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, ID_LOGISTICA, FECHA)
			VALUES(1, 17, 25982761252, '07-08-2024')

----
----- DETALLE PEDIDO

INSERT INTO DETALLES_PEDIDOS(ID_DETALLE_PEDIDO, ID_PEDIDO, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD)
			VALUES(1,1,3, 1, NULL, 25)

INSERT INTO DETALLES_PEDIDOS(ID_DETALLE_PEDIDO, ID_PEDIDO, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD)
			VALUES(2,1,4, 1, NULL, 10)

INSERT INTO DETALLES_PEDIDOS(ID_DETALLE_PEDIDO, ID_PEDIDO, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD)
			VALUES(3,1, 9, 1, NULL, 15)

INSERT INTO DETALLES_PEDIDOS(ID_DETALLE_PEDIDO, ID_PEDIDO, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD)
			VALUES(4,1, 19, 1, NULL, 12)


---
---- COTIZACIONES


INSERT INTO COTIZACIONES(ID_COTIZACION, ID_PERSONAL_CARGOS_ESTABLECIMIENTOS, ID_LOGISTICA, FECHA)
			VALUES(1, 17, 25982761252, '07-08-2024')


---
---- COTIZACIONES DETALLES

INSERT INTO DETALLES_COTIZACION(ID_DETALLE_COTIZACION, ID_COTIZACION, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD)
			VALUES(1,1,3, 1, NULL, 25)

INSERT INTO DETALLES_COTIZACION(ID_DETALLE_COTIZACION, ID_COTIZACION, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD)
			VALUES(2,1,4, 1, NULL, 10)

INSERT INTO DETALLES_COTIZACION(ID_DETALLE_COTIZACION, ID_COTIZACION, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD)
			VALUES(3,1, 9, 1, NULL, 15)

INSERT INTO DETALLES_COTIZACION(ID_DETALLE_COTIZACION, ID_COTIZACION, ID_MEDICAMENTO_OBRA_SOCIAL, ID_PROVEEDOR, ID_PRODUCTO, CANTIDAD)
			VALUES(4,1, 19, 1, NULL, 12)


---
---- INVENTARIO COTIZACIONES

INSERT INTO INVENTARIOS(ID_INVENTARIO, CANTIDAD, FECHA, ID_TIPO_MOV, ID_STOCK)
			VALUES(4, 25, '07-08-2024', 1,  3)
INSERT INTO INVENTARIOS(ID_INVENTARIO, CANTIDAD, FECHA, ID_TIPO_MOV, ID_STOCK)
			VALUES(5, 10, '07-08-2024', 1,  4)
INSERT INTO INVENTARIOS(ID_INVENTARIO, CANTIDAD, FECHA, ID_TIPO_MOV, ID_STOCK)
			VALUES(6, 15, '07-08-2024', 1,  9)
INSERT INTO INVENTARIOS(ID_INVENTARIO, CANTIDAD, FECHA, ID_TIPO_MOV, ID_STOCK)
			VALUES(7, 12, '07-08-2024', 1,  19)

