CREATE DATABASE Farmaceutica

go
use Farmaceutica
go

-- TABLAS SATELITE

CREATE TABLE PAISES(
	ID_PAIS INT IDENTITY(5,5),
	PAIS VARCHAR(50)NOT NULL,
	CONSTRAINT PK_PAISES PRIMARY KEY(ID_PAIS)
)

CREATE TABLE PROVINCIAS(
	ID_PROVINCIA INT IDENTITY(5,5),
	PROVINCIA VARCHAR(50)NOT NULL,
	ID_PAIS INT NOT NULL,

	CONSTRAINT PK_PROVINCIAS PRIMARY KEY(ID_PROVINCIA),
	CONSTRAINT FK_PROVINCIAS_PAISES FOREIGN KEY(ID_PAIS)
	REFERENCES PAISES(ID_PAIS)
)

CREATE TABLE CIUDADES(
	ID_CIUDAD INT IDENTITY(5,5),
	CIUDAD VARCHAR(50)NOT NULL,
	ID_PROVINCIA INT NOT NULL,

	CONSTRAINT PK_CIUDADES PRIMARY KEY(ID_CIUDAD),
	CONSTRAINT FK_CIUDADES_PROVINCIAS FOREIGN KEY(ID_PROVINCIA)
	REFERENCES PROVINCIAS(ID_PROVINCIA)
)

CREATE TABLE BARRIOS(
	ID_BARRIO INT IDENTITY(5,5),
	BARRIO VARCHAR(50)NOT NULL,
	ID_CIUDAD INT NOT NULL,
	CONSTRAINT PK_BARRIOS PRIMARY KEY(ID_BARRIO),
	CONSTRAINT FK_BARRIOS_CIUDADES FOREIGN KEY(ID_CIUDAD)
	REFERENCES CIUDADES(ID_CIUDAD)
)

CREATE TABLE ESTABLECIMIENTOS (
    ID_ESTABLECIMIENTO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
    ID_BARRIO INT NOT NULL,
    CONSTRAINT PK_ESTABLECIMIENTO PRIMARY KEY (ID_ESTABLECIMIENTO),
    CONSTRAINT FK_ESTABLECIMIENTO_BARRIOS FOREIGN KEY (ID_BARRIO) 
        REFERENCES BARRIOS(ID_BARRIO)
);

CREATE TABLE TIPOS_PRODUCTOS (
    ID_TIPO_PRODUCTO INT NOT NULL,
    TIPO_PRODUCTO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPOS_PRODUCTOS PRIMARY KEY (ID_TIPO_PRODUCTO)
);


CREATE TABLE PRESENTACIONES (
    ID_PRESENTACION INT NOT NULL,
    PRESENTACION VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PRESENTACIONES PRIMARY KEY (ID_PRESENTACION)
);

CREATE TABLE VIAS_ADMINISTRACION(
	ID_VIA INT NOT NULL,
	VIA VARCHAR(100) NOT NULL

	CONSTRAINT PK_VIAS PRIMARY KEY(ID_VIA)
);

CREATE TABLE PRESENTACIONES_VIAS(
	ID_PRESENTACION_VIA INT NOT NULL,
	ID_PRESENTACION INT NOT NULL,
	ID_VIA INT NOT NULL

	CONSTRAINT PK_PRESENTACIONES_VIAS PRIMARY KEY(ID_PRESENTACION_VIA)
	CONSTRAINT FK_PRESENTACIONES_VIAS_PRESENTACIONES FOREIGN KEY(ID_PRESENTACION)
		REFERENCES PRESENTACIONES(ID_PRESENTACION),
	CONSTRAINT FK_PRESENTACIONES_VIAS_VIAS FOREIGN KEY(ID_VIA)
		REFERENCES VIAS_ADMINISTRACION(ID_VIA)
);

CREATE TABLE CARGOS (
    ID_CARGO INT NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CARGOS PRIMARY KEY (ID_CARGO)
);

CREATE TABLE TIPOS_MOVIMIENTOS (
    ID_TIPO_MOV INT NOT NULL,
    MOVIMIENTO VARCHAR(100) NOT NULL,
	MODIFICADOR int not null,
    CONSTRAINT PK_TIPOS_MOVIMIENTOS PRIMARY KEY (ID_TIPO_MOV)
);

CREATE TABLE TIPOS_CONTACTOS (
    ID_TIPO_CONTACTO INT NOT NULL IDENTITY (1,1),
    TIPO_CONTACTO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPOS_CONTACTOS PRIMARY KEY (ID_TIPO_CONTACTO)
);

CREATE TABLE TIPOS_DOCUMENTOS (
    ID_TIPO_DOC INT NOT NULL IDENTITY(1,1),
    TIPO_DOCUMENTO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPOS_DOC PRIMARY KEY (ID_TIPO_DOC)
);

CREATE TABLE TIPOS_GENEROS (
    ID_GENERO INT NOT NULL,
    NOMBRE_GENERO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_GENEROS PRIMARY KEY (ID_GENERO)
);

CREATE TABLE LABORATORIOS (
    ID_LABORATORIO INT NOT NULL,
    NOMBRE_LABORATORIO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_LABORATORIOS PRIMARY KEY (ID_LABORATORIO)
);

CREATE TABLE MARCAS (
    ID_MARCA INT NOT NULL,
    NOMBRE_MARCA VARCHAR(100) NOT NULL,
    CONSTRAINT PK_MARCAS PRIMARY KEY (ID_MARCA)
);

CREATE TABLE MONODROGAS (
    ID_MONODROGA INT NOT NULL,
    MONODROGA VARCHAR(100) NOT NULL,
    CONSTRAINT PK_MONODROGAS PRIMARY KEY (ID_MONODROGA)
);

CREATE TABLE ESPECIALIDADES (
    ID_TIPO_ESPECIALIDAD INT NOT NULL,
    ESPECIALIDAD VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ESPECIALIDADES PRIMARY KEY (ID_TIPO_ESPECIALIDAD)
);

CREATE TABLE TIPOS_PAGOS (
    ID_TIPO_PAGO INT identity(1,1),
    TIPO_PAGO VARCHAR(100) NOT NULL,
	DESCUENTO DECIMAL(5,2) NULL
    CONSTRAINT PK_TIPOS_PAGOS PRIMARY KEY (ID_TIPO_PAGO)
);

-- PRODUCTOS

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_MARCA INT,
    TIPO_PRODUCTO INT NOT NULL,
    DESCRIPCION VARCHAR(255),
    PRECIO DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTOS_TIPOS_PRODUCTOS FOREIGN KEY (TIPO_PRODUCTO) 
        REFERENCES TIPOS_PRODUCTOS(ID_TIPO_PRODUCTO),
    CONSTRAINT FK_PRODUCTOS_MARCAS FOREIGN KEY (ID_MARCA) 
        REFERENCES MARCAS(ID_MARCA)
);

CREATE TABLE MEDICAMENTOS (
    ID_MEDICAMENTO INT NOT NULL,
    ID_MONODROGA INT NOT NULL,
    NOMBRE_COMERCIAL VARCHAR(100) NOT NULL,
    ID_LABORATORIO INT NOT NULL,
    ID_MARCA INT NOT NULL,
    VENTA_LIBRE BIT NOT NULL,
    ID_PRESENTACION_VIA INT NOT NULL,
    DESCRIPCION VARCHAR(255),
    PRECIO DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PK_MEDICAMENTOS PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT FK_MEDICAMENTOS_MONODROGAS FOREIGN KEY (ID_MONODROGA) 
        REFERENCES MONODROGAS(ID_MONODROGA),
    CONSTRAINT FK_MEDICAMENTOS_LABORATORIOS FOREIGN KEY (ID_LABORATORIO) 
        REFERENCES LABORATORIOS(ID_LABORATORIO),
    CONSTRAINT FK_MEDICAMENTOS_MARCAS FOREIGN KEY (ID_MARCA) 
        REFERENCES MARCAS(ID_MARCA),
    CONSTRAINT FK_MEDICAMENTOS_PRESENTACIONES_VIAS FOREIGN KEY (ID_PRESENTACION_VIA) 
        REFERENCES PRESENTACIONES_VIAS(ID_PRESENTACION_VIA)
);

CREATE TABLE MEDICAMENTOS_LOTES (
    ID_MEDICAMENTO_LOTE INT NOT NULL,
    ID_MEDICAMENTO INT NOT NULL,
    LOTE VARCHAR(50) NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    CONSTRAINT PK_MEDICAMENTOS_LOTES PRIMARY KEY (ID_MEDICAMENTO_LOTE),
    CONSTRAINT FK_MEDICAMENTOS_LOTES_MEDICAMENTOS FOREIGN KEY (ID_MEDICAMENTO) 
        REFERENCES MEDICAMENTOS(ID_MEDICAMENTO)
);

CREATE TABLE OBRA_SOCIAL (
    ID_OBRA_SOCIAL INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_OBRA_SOCIAL PRIMARY KEY (ID_OBRA_SOCIAL)
);

CREATE TABLE TIPOS_COBERTURAS (
    ID_TIPO_COBERTURA INT NOT NULL,
    ID_OBRA_SOCIAL INT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    CONSTRAINT PK_TIPOS_COBERTURAS PRIMARY KEY (ID_TIPO_COBERTURA),
    CONSTRAINT FK_TIPOS_COBERTURAS_OBRA_SOCIAL FOREIGN KEY (ID_OBRA_SOCIAL) 
        REFERENCES OBRA_SOCIAL(ID_OBRA_SOCIAL)
);

CREATE TABLE MEDICAMENTOS_OBRA_SOCIAL (
    ID_MEDICAMENTO_OBRA_SOCIAL INT NOT NULL,
    ID_MEDICAMENTO INT NOT NULL,
    ID_TIPO_COBERTURA INT NOT NULL,
    DESCUENTO DECIMAL(5, 2) NOT NULL,
    FECHA_COBERTURA DATE NOT NULL,
    ID_CIUDAD INT NOT NULL,
    CONSTRAINT PK_MEDICAMENTOS_OBRA_SOCIAL PRIMARY KEY (ID_MEDICAMENTO_OBRA_SOCIAL),
    CONSTRAINT FK_MEDICAMENTOS_OBRA_SOCIAL_MEDICAMENTOS FOREIGN KEY (ID_MEDICAMENTO) 
        REFERENCES MEDICAMENTOS(ID_MEDICAMENTO),
    CONSTRAINT FK_MEDICAMENTOS_OBRA_SOCIAL_TIPOS_COBERTURAS FOREIGN KEY (ID_TIPO_COBERTURA) 
        REFERENCES TIPOS_COBERTURAS(ID_TIPO_COBERTURA),
    CONSTRAINT FK_MEDICAMENTOS_OBRA_SOCIAL_CIUDADES FOREIGN KEY (ID_CIUDAD) 
        REFERENCES CIUDADES(ID_CIUDAD)
);

-- ENTIDADES/PERSONAS

CREATE TABLE CLIENTES (
    ID_CLIENTE INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
    ID_BARRIO INT NOT NULL,
    TIPO_DOC INT NOT NULL,
    NRO_DOC VARCHAR(20) NOT NULL,
	ID_GENERO INT
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT FK_CLIENTES_BARRIOS FOREIGN KEY (ID_BARRIO) 
        REFERENCES BARRIOS(ID_BARRIO),
    CONSTRAINT FK_CLIENTES_TIPO_DOC FOREIGN KEY (TIPO_DOC) 
        REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOC),
	CONSTRAINT FK_CLIENTES_GENEROS FOREIGN KEY (ID_GENERO)
		REFERENCES TIPOS_GENEROS (ID_GENERO)
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT NOT NULL,
    RAZON_SOCIAL VARCHAR(100) NOT NULL,
    CUIT VARCHAR(20) NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
    ID_BARRIO INT NOT NULL,
    ACTIVO BIT NOT NULL,
    CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT FK_PROVEEDORES_BARRIOS FOREIGN KEY (ID_BARRIO) 
        REFERENCES BARRIOS(ID_BARRIO)
);

CREATE TABLE EMPRESA_LOGISTICA (
    CUIT VARCHAR(20) NOT NULL,
    NOMBRE_EMPRESA VARCHAR(100) NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
    ID_BARRIO INT NOT NULL,
    CONSTRAINT PK_EMPRESA_LOGISTICA PRIMARY KEY (CUIT),
    CONSTRAINT FK_EMPRESA_LOGISTICA_BARRIOS FOREIGN KEY (ID_BARRIO) 
        REFERENCES BARRIOS(ID_BARRIO)
);

CREATE TABLE COBERTURAS_CLIENTES (
    ID_BENEFICIARIO INT NOT NULL,
    ID_TIPO_COBERTURA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT PK_COBERTURAS_CLIENTES PRIMARY KEY (ID_BENEFICIARIO),
    CONSTRAINT FK_COBERTURAS_CLIENTES_TIPOS_COBERTURAS FOREIGN KEY (ID_TIPO_COBERTURA) 
        REFERENCES TIPOS_COBERTURAS(ID_TIPO_COBERTURA),
    CONSTRAINT FK_COBERTURAS_CLIENTES_CLIENTES FOREIGN KEY (ID_CLIENTE) 
        REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE PERSONAL (
    ID_PERSONAL INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10),
	ID_BARRIO INT NOT NULL,
    TIPO_DOC INT NOT NULL,
    NRO_DOC VARCHAR(20) NOT NULL,
	ID_GENERO INT
    CONSTRAINT PK_PERSONAL PRIMARY KEY (ID_PERSONAL),
    CONSTRAINT FK_PERSONAL_TIPO_DOC FOREIGN KEY (TIPO_DOC)
        REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOC),
	CONSTRAINT FK_PERSONAL_GENEROS FOREIGN KEY (ID_GENERO)
		REFERENCES TIPOS_GENEROS (ID_GENERO),
	CONSTRAINT FK_PERSONAL_BARRIOS FOREIGN KEY (ID_BARRIO)
		REFERENCES BARRIOS (ID_BARRIO)
);

CREATE TABLE MEDICOS (
    MATRICULA VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    ID_TIPO_ESPECIALIDAD INT NOT NULL,
    CONSTRAINT PK_MEDICOS PRIMARY KEY (MATRICULA),
    CONSTRAINT FK_MEDICOS_ESPECIALIDADES FOREIGN KEY (ID_TIPO_ESPECIALIDAD) 
        REFERENCES ESPECIALIDADES(ID_TIPO_ESPECIALIDAD)
);

CREATE TABLE PERSONAL_CARGOS_ESTABLECIMIENTOS (
    ID_PERSONAL_CARGOS_ESTABLECIMIENTOS INT NOT NULL,
    ID_PERSONAL INT NOT NULL,
    ID_CARGO INT NOT NULL,
    CONSTRAINT PK_PERSONAL_CARGOS_ESTABLECIMIENTOS PRIMARY KEY (ID_PERSONAL_CARGOS_ESTABLECIMIENTOS),
    CONSTRAINT FK_PERSONAL_CARGOS_ESTABLECIMIENTOS_PERSONAL FOREIGN KEY (ID_PERSONAL) 
        REFERENCES PERSONAL(ID_PERSONAL),
    CONSTRAINT FK_PERSONAL_CARGOS_ESTABLECIMIENTOS_CARGOS FOREIGN KEY (ID_CARGO) 
        REFERENCES CARGOS(ID_CARGO)
);

CREATE TABLE CONTACTOS (
	ID_CONTACTO INT IDENTITY(1,1),
	ID_TIPO_CONTACTO INT NOT NULL,
	ID_PERSONAL INT,
	ID_PROVEEDOR INT,
	ID_LOGISTICA VARCHAR(20),
	ID_ESTABLECIMIENTO INT,
	ID_CLIENTE INT,
	CONTACTO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CONTACTOS PRIMARY KEY (ID_CONTACTO),
	CONSTRAINT FK_CONTACTOS_TIPOS_CONTACTOS FOREIGN KEY (ID_TIPO_CONTACTO)
		REFERENCES TIPOS_CONTACTOS(ID_TIPO_CONTACTO),
	CONSTRAINT FK_CONTACTOS_PERSONAL FOREIGN KEY (ID_PERSONAL)
		REFERENCES PERSONAL(ID_PERSONAL),
	CONSTRAINT FK_CONTACTOS_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR)
		REFERENCES PROVEEDORES(ID_PROVEEDOR),
	CONSTRAINT FK_CONTACTOS_EMPRESA_LOGISTICA FOREIGN KEY (ID_LOGISTICA)
		REFERENCES EMPRESA_LOGISTICA(CUIT)
);

CREATE TABLE STOCKS(
	ID_STOCK INT,
	FECHA DATE NOT NULL,
	CANTIDAD INT NOT NULL,
	CANTIDAD_MINIMA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	ID_ESTABLECIMIENTO INT NOT NULL,
	CONSTRAINT PK_STOCKS PRIMARY KEY (ID_STOCK),
	CONSTRAINT FK_STOCKS_PRODUCTOS FOREIGN KEY (ID_PRODUCTO)
		REFERENCES PRODUCTOS(ID_PRODUCTO),
	CONSTRAINT FK_STOCKS_ESTABLECIMIENTOS FOREIGN KEY (ID_ESTABLECIMIENTO)
		REFERENCES ESTABLECIMIENTOS(ID_ESTABLECIMIENTO)
);

CREATE TABLE INVENTARIOS(
	ID_INVENTARIO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA DATE NOT NULL,
	ID_TIPO_MOV INT NOT NULL,
	ID_STOCK INT NOT NULL,
	CONSTRAINT PK_INVENTARIOS PRIMARY KEY (ID_INVENTARIO),
	CONSTRAINT FK_INVENTARIOS_TIPOS_MOVIMIENTOS FOREIGN KEY (ID_TIPO_MOV)
		REFERENCES TIPOS_MOVIMIENTOS(ID_TIPO_MOV),
	CONSTRAINT FK_INVENTARIOS_STOCKS FOREIGN KEY (ID_STOCK)
		REFERENCES STOCKS(ID_STOCK)
);

CREATE TABLE PEDIDOS(
	ID_PEDIDO INT NOT NULL,
	ID_PERSONAL_CARGOS_ESTABLECIMIENTOS INT NOT NULL,
	ID_LOGISTICA VARCHAR(20) NOT NULL,
	FECHA DATE NOT NULL,
	CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_PEDIDOS_PERSONAL_CARGOS_ESTABLECIMIENTOS FOREIGN KEY (ID_PERSONAL_CARGOS_ESTABLECIMIENTOS)
		REFERENCES PERSONAL_CARGOS_ESTABLECIMIENTOS(ID_PERSONAL_CARGOS_ESTABLECIMIENTOS),
	CONSTRAINT FK_PEDIDOS_EMPRESA_LOGISTICA FOREIGN KEY (ID_LOGISTICA)
		REFERENCES EMPRESA_LOGISTICA(CUIT)
);

CREATE TABLE DETALLES_PEDIDOS(
	ID_DETALLE_PEDIDO INT NOT NULL,
	ID_MEDICAMENTO_OBRA_SOCIAL INT NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (ID_DETALLE_PEDIDO),
	CONSTRAINT FK_DETALLE_PEDIDO_MEDICAMENTOS_OBRA_SOCIAL FOREIGN KEY (ID_MEDICAMENTO_OBRA_SOCIAL)
		REFERENCES MEDICAMENTOS_OBRA_SOCIAL(ID_MEDICAMENTO_OBRA_SOCIAL),
	CONSTRAINT FK_DETALLES_PEDIDOS_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR)
		REFERENCES PROVEEDORES(ID_PROVEEDOR),
	CONSTRAINT FK_DETALLES_PEDIDOS_PRODUCTOS FOREIGN KEY (ID_PRODUCTO)
		REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE FACTURAS (
	ID_FACTURA INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_PERSONAL_CARGOS_ESTABLECIMIENTOS INT,
	FECHA DATE

	CONSTRAINT PK_FACTURAS PRIMARY KEY(ID_FACTURA),
	CONSTRAINT FK_FACTURAS_CLIENTES FOREIGN KEY(ID_CLIENTE)
		REFERENCES CLIENTES(ID_CLIENTE),
	CONSTRAINT FK_FACTURAS_PERSONAL FOREIGN KEY(ID_PERSONAL_CARGOS_ESTABLECIMIENTOS)
		REFERENCES PERSONAL_CARGOS_ESTABLECIMIENTOS(ID_PERSONAL_CARGOS_ESTABLECIMIENTOS)
);


CREATE TABLE DISPENSACIONES(
	ID_DISPENSACION INT NOT NULL,
	ID_FACTURA INT NOT NULL,
	ID_MEDICAMENTO_OBRA_SOCIAL INT NULL,
	ID_PRODUCTO INT NULL,
	DESCUENTO_PRODUCTO DECIMAL(10, 2) NULL,
	PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
	CANTIDAD INT NOT NULL,
	MATRICULA VARCHAR(20) NULL,
	CODIGO_VALIDACION VARCHAR(20)

	CONSTRAINT PK_DISPENSACIONES PRIMARY KEY(ID_DISPENSACION),
	CONSTRAINT FK_DISPENSACIONES_FACTURAS FOREIGN KEY(ID_FACTURA)
		REFERENCES FACTURAS(ID_FACTURA),
	CONSTRAINT FK_DISPENSACIONES_MEDICAMENTO_OBRA_SOCIAL FOREIGN KEY(ID_MEDICAMENTO_OBRA_SOCIAL)
		REFERENCES MEDICAMENTOS_OBRA_SOCIAL(ID_MEDICAMENTO_OBRA_SOCIAL),
	CONSTRAINT FK_DISPENSACIONES_PRODUCTOS FOREIGN KEY(ID_PRODUCTO)
		REFERENCES PRODUCTOS(ID_PRODUCTO),
	CONSTRAINT FK_DISPENSACIONES_MEDICOS FOREIGN KEY(MATRICULA)
		REFERENCES MEDICOS(MATRICULA)
);

CREATE TABLE DETALLES_FACTURAS_OBRA_SOCIAL(
	ID_DETALLE_FACTURA_OBRA_SOCIAL INT NOT NULL,
	ID_DISPENSACION INT NOT NULL

	CONSTRAINT PK_DETALLES_FACTURAS_OBRA_SOCIAL PRIMARY KEY(ID_DETALLE_FACTURA_OBRA_SOCIAL),
	CONSTRAINT FK_DETALLES_FACTURAS_OBRA_SOCIAL_DISPENSACIONES FOREIGN KEY(ID_DISPENSACION)
		REFERENCES DISPENSACIONES(ID_DISPENSACION)
);

CREATE TABLE FACTURAS_TIPOS_PAGOS(
	ID_FACTURA_TIPO_PAGO INT NOT NULL,
	ID_FACTURA INT NOT NULL,
	ID_TIPO_PAGO INT NULL,
	PORCENTAJE_PAGO DECIMAL(5,2) NULL,
	ES_CUOTAS BIT NULL,
	CANTIDAD_CUOTAS INT NULL

	CONSTRAINT PK_FACT_TIPOS_PAGOS PRIMARY KEY(ID_FACTURA_TIPO_PAGO)
	CONSTRAINT FK_FACT_TIPOS_PAGOS_FACT FOREIGN KEY(ID_FACTURA)
		REFERENCES FACTURAS(ID_FACTURA),
	CONSTRAINT FK_FACT_TIPOS_PAGOS_TIPOS_PAGOS FOREIGN KEY(ID_TIPO_PAGO)
		REFERENCES TIPOS_PAGOS(ID_TIPO_PAGO)
);

CREATE TABLE TIPOS_PAGOS_DESCUENTOS(
	ID_TIPOS_PAGOS_DESCUENTOS INT NOT NULL,
	ID_TIPO_PAGO INT NOT NULL,
	DESCUENTO DECIMAL(10,2) NOT NULL,
	DESCRIPCION VARCHAR(50) NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE NOT NULL

	CONSTRAINT PK_TIPOS_PAGOS_DESCUENTOS PRIMARY KEY(ID_TIPOS_PAGOS_DESCUENTOS)
	CONSTRAINT FK_DESCUENTOS_TIPOS_PAGOS FOREIGN KEY(ID_TIPO_PAGO)
		REFERENCES TIPOS_PAGOS(ID_TIPO_PAGO)
);


CREATE TABLE COTIZACIONES(
	ID_COTIZACION INT NOT NULL,
	ID_PERSONAL_CARGOS_ESTABLECIMIENTOS INT NOT NULL,
	ID_LOGISTICA VARCHAR(20) NOT NULL,
	FECHA DATE NOT NULL,
	CONSTRAINT PK_COTIZACIONES PRIMARY KEY (ID_COTIZACION),
	CONSTRAINT FK_COTIZACIONES_PERSONAL_CARGOS_ESTABLECIMIENTOS FOREIGN KEY (ID_PERSONAL_CARGOS_ESTABLECIMIENTOS)
		REFERENCES PERSONAL_CARGOS_ESTABLECIMIENTOS(ID_PERSONAL_CARGOS_ESTABLECIMIENTOS),
	CONSTRAINT FK_COTIZACIONES_EMPRESA_LOGISTICA FOREIGN KEY (ID_LOGISTICA)
		REFERENCES EMPRESA_LOGISTICA(CUIT)
);

CREATE TABLE DETALLES_COTIZACION(
	ID_DETALLE_COTIZACION INT NOT NULL,
	ID_MEDICAMENTO_OBRA_SOCIAL INT NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	CONSTRAINT PK_DETALLE_COTIZACIONES PRIMARY KEY (ID_DETALLE_COTIZACION),
	CONSTRAINT FK_DETALLE_COTIZACIONES_MEDICAMENTOS_OBRA_SOCIAL FOREIGN KEY (ID_MEDICAMENTO_OBRA_SOCIAL)
		REFERENCES MEDICAMENTOS_OBRA_SOCIAL(ID_MEDICAMENTO_OBRA_SOCIAL),
	CONSTRAINT FK_DETALLES_COTIZACIONES_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR)
		REFERENCES PROVEEDORES(ID_PROVEEDOR),
	CONSTRAINT FK_DETALLES_COTIZACIONES_PRODUCTOS FOREIGN KEY (ID_PRODUCTO)
		REFERENCES PRODUCTOS(ID_PRODUCTO)
);

--------------------------------------------------------------------------------------------------
--TIPOS_DOCUMENTOS

INSERT INTO TIPOS_DOCUMENTOS(tipo_documento)
	VALUES ('DNI');
	
INSERT INTO TIPOS_DOCUMENTOS(tipo_documento)
	VALUES ('LE');
	
INSERT INTO TIPOS_DOCUMENTOS(tipo_documento)
	VALUES ('LC');
	
INSERT INTO TIPOS_DOCUMENTOS(tipo_documento)
	VALUES ('Cedula');
	
INSERT INTO TIPOS_DOCUMENTOS(tipo_documento)
	VALUES ('Pasaporte');
						
--TIPOS_CONTACTOS

INSERT INTO TIPOS_CONTACTOS(TIPO_CONTACTO)
	VALUES ('Celular');

INSERT INTO TIPOS_CONTACTOS(TIPO_CONTACTO)
	VALUES ('Telefono Fijo');

INSERT INTO TIPOS_CONTACTOS(TIPO_CONTACTO)
	VALUES ('Mail');

INSERT INTO TIPOS_CONTACTOS(TIPO_CONTACTO)
	VALUES ('Instagram');

INSERT INTO TIPOS_CONTACTOS(TIPO_CONTACTO)
	VALUES ('X');

--PAISES
INSERT INTO PAISES(PAIS)
				VALUES('Argentina');
				
INSERT INTO PAISES(PAIS)
				VALUES('Brasil');
				
INSERT INTO PAISES(PAIS)
				VALUES('Chile');
				
INSERT INTO PAISES(PAIS)
				VALUES('Uruguay');
				
INSERT INTO PAISES(PAIS)
				VALUES('Paraguay');
				
INSERT INTO PAISES(PAIS)
				VALUES('Perú');
				
INSERT INTO PAISES(PAIS)
				VALUES('Bolivia');
				
INSERT INTO PAISES(PAIS)
				VALUES('Ecuador');
				
INSERT INTO PAISES(PAIS)
				VALUES('Venezuela');
				
INSERT INTO PAISES(PAIS)
				VALUES('Colombia');

--PROVINCIAS

INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Cordoba', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Buenos Aires', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Tucuman', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Santa Fe', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Santa Cruz', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Misiones', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Entre Rios', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Jujuy', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Río Negro', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Mendoza', 5);
					
INSERT INTO PROVINCIAS(PROVINCIA, id_pais)
					VALUES('Ciudad Autonoma de Buenos Aires', 5);		
					
--CIUDADES

INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('Cordoba', 5);
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('Rio Cuarto', 5);
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('Rosario', 20);
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('La Plata', 10);	
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('San Miguel de Tucuman', 15);
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('El Calafate', 25);
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('Posadas', 30);
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('San Salvador de Jujuy', 40);
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('San Carlos de Bariloche', 45);
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('Mendoza', 50);
					
INSERT INTO CIUDADES(CIUDAD, id_provincia)
					VALUES('Ciudad de Buenos Aires', 55);
					

--BARRIOS

INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('General Paz', 5);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Alberdi', 5);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Alta Cordoba', 5);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Juniors', 5);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Cerro de las Rosas', 5);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Luis Agote', 15);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Santa Teodora', 10);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Melipal', 45);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Las Quintas', 20);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('25 de Mayo', 35);
					
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Moron', 55);
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('San Javier', 55);
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('San josé', 55);
INSERT INTO BARRIOS(BARRIO, id_ciudad)
					VALUES('Villa Adela', 5);
				

---					

--TIPOS_PAGOS

INSERT INTO TIPOS_PAGOS(TIPO_PAGO, DESCUENTO)
	VALUES ('Efectivo', 0.10);
	
INSERT INTO TIPOS_PAGOS(TIPO_PAGO, DESCUENTO)
	VALUES ('QR Mercado Pago', null);
	
INSERT INTO TIPOS_PAGOS(TIPO_PAGO, DESCUENTO)
	VALUES ('Transferencia', null);
	
INSERT INTO TIPOS_PAGOS(TIPO_PAGO, DESCUENTO)
	VALUES ('Tarjeta de Credito', null);
	
INSERT INTO TIPOS_PAGOS(TIPO_PAGO, DESCUENTO)
	VALUES ('Tarjeta de Debito', null);
	
INSERT INTO TIPOS_PAGOS(TIPO_PAGO, DESCUENTO)
	VALUES ('QR MODO', null);

---
-- TIPOS PRODUCTOS

INSERT INTO TIPOS_PRODUCTOS (ID_TIPO_PRODUCTO, TIPO_PRODUCTO)
	VALUES (1, 'Alimentos');

INSERT INTO TIPOS_PRODUCTOS (ID_TIPO_PRODUCTO, TIPO_PRODUCTO)
	VALUES (2, 'Dermocosmética');

INSERT INTO TIPOS_PRODUCTOS (ID_TIPO_PRODUCTO, TIPO_PRODUCTO)
	VALUES (3, 'Juguetes');

INSERT INTO TIPOS_PRODUCTOS (ID_TIPO_PRODUCTO, TIPO_PRODUCTO)
	VALUES (4, 'Hogar');

INSERT INTO TIPOS_PRODUCTOS (ID_TIPO_PRODUCTO, TIPO_PRODUCTO)
	VALUES (5, 'Productos de higiene');

INSERT INTO TIPOS_PRODUCTOS (ID_TIPO_PRODUCTO, TIPO_PRODUCTO)
	VALUES (6, 'Bebés');

INSERT INTO TIPOS_PRODUCTOS (ID_TIPO_PRODUCTO, TIPO_PRODUCTO)
	VALUES (7, 'Dermocosmética');

INSERT INTO TIPOS_PRODUCTOS (ID_TIPO_PRODUCTO, TIPO_PRODUCTO)
	VALUES (8, 'Electrónica');

---
-- TIPOS MOVIMIENTOS

INSERT INTO TIPOS_MOVIMIENTOS(ID_TIPO_MOV, MOVIMIENTO, MODIFICADOR)
			VALUES(1, 'Compra', 1);

INSERT INTO TIPOS_MOVIMIENTOS(ID_TIPO_MOV, MOVIMIENTO, MODIFICADOR)
			VALUES(2, 'Venta', -1);

INSERT INTO TIPOS_MOVIMIENTOS(ID_TIPO_MOV, MOVIMIENTO, MODIFICADOR)
			VALUES(3, 'Vencimiento', -1);

INSERT INTO TIPOS_MOVIMIENTOS(ID_TIPO_MOV, MOVIMIENTO, MODIFICADOR)
			VALUES(4, 'Falla', -1);

INSERT INTO TIPOS_MOVIMIENTOS(ID_TIPO_MOV, MOVIMIENTO, MODIFICADOR)
			VALUES(5, 'Robo', -1);

INSERT INTO TIPOS_MOVIMIENTOS(ID_TIPO_MOV, MOVIMIENTO, MODIFICADOR)
			VALUES(6, 'Rotura', -1);

INSERT INTO TIPOS_MOVIMIENTOS(ID_TIPO_MOV, MOVIMIENTO, MODIFICADOR)
			VALUES(7, 'Retiro del mercado', -1);

---
-- OBRAS SOCIALES

INSERT INTO OBRA_SOCIAL(ID_OBRA_SOCIAL, NOMBRE)
			VALUES(1, 'Swiss Medical');
INSERT INTO OBRA_SOCIAL(ID_OBRA_SOCIAL, NOMBRE)
			VALUES(2, 'GEA');
INSERT INTO OBRA_SOCIAL(ID_OBRA_SOCIAL, NOMBRE)
			VALUES(3, 'Medifé');
INSERT INTO OBRA_SOCIAL(ID_OBRA_SOCIAL, NOMBRE)
			VALUES(4, 'Sancor Salud');
INSERT INTO OBRA_SOCIAL(ID_OBRA_SOCIAL, NOMBRE)
			VALUES(5, 'OSDE');
INSERT INTO OBRA_SOCIAL(ID_OBRA_SOCIAL, NOMBRE)
			VALUES(6, 'DASPU');
INSERT INTO OBRA_SOCIAL(ID_OBRA_SOCIAL, NOMBRE)
			VALUES(7, 'PAMI');

---
-- GENEROS

INSERT INTO TIPOS_GENEROS (ID_GENERO, NOMBRE_GENERO)
    VALUES (1, 'Masculino');

INSERT INTO TIPOS_GENEROS (ID_GENERO, NOMBRE_GENERO)
    VALUES (2, 'Femenino');

INSERT INTO TIPOS_GENEROS (ID_GENERO, NOMBRE_GENERO)
    VALUES (3, 'No Binario');

INSERT INTO TIPOS_GENEROS (ID_GENERO, NOMBRE_GENERO)
    VALUES (4, 'Prefiero no decir');

INSERT INTO TIPOS_GENEROS (ID_GENERO, NOMBRE_GENERO)
    VALUES (5, 'Otro');

